local pick_files = function()
  if vim.fn.finddir(".git", vim.fn.getcwd() .. ";") ~= "" then
    Snacks.picker.git_files()
  else
    Snacks.picker.files()
  end
end

local pick_grep = function()
  if vim.fn.finddir(".git", vim.fn.getcwd() .. ";") ~= "" then
    Snacks.picker.git_grep()
  else
    Snacks.picker.grep()
  end
end

vim.keymap.set("n", "<C-n>", "<cmd>bnext<CR>", { desc = "Next buffer" })
vim.keymap.set("n", "<C-p>", "<cmd>bprevious<CR>", { desc = "Previous buffer" })
vim.keymap.set("n", "<leader>e", vim.diagnostic.open_float, { desc = "Open diagnostic float" })
vim.keymap.set("x", "<leader>s", ":'<,'>sort i<CR>", { desc = "Sort selection" })
vim.keymap.set("n", "<leader>d", function()
  local win_config = vim.api.nvim_win_get_config(0)
  if win_config.relative ~= "" then
    vim.api.nvim_win_close(0, true)
  else
    Snacks.bufdelete()
  end
end, { desc = "Smart close" })
vim.keymap.set("n", "<leader>D", function()
  Snacks.bufdelete(0, { force = true })
end, { desc = "Force delete buffer" })

vim.keymap.set("n", "<leader>p", '"+p', { desc = "Paste from clipboard" })
vim.keymap.set("n", "<leader>P", '"+P', { desc = "Paste from clipboard (before)" })
vim.keymap.set("n", "<leader>y", '"+y', { desc = "Yank to clipboard" })
vim.keymap.set("x", "<leader>y", '"+y', { desc = "Yank to clipboard" })

vim.keymap.set("n", "<leader>un", function()
  vim.o.number = not vim.o.number
  vim.o.relativenumber = not vim.o.relativenumber
end, { desc = "Toggle line numbers" })

vim.keymap.set("n", "<leader>wo", "<C-w>o", { desc = "Close other windows" })
vim.keymap.set("n", "<leader>wp", "<cmd>pclose<CR>", { desc = "Close preview" })
vim.keymap.set("n", "<leader>wz", "<C-w>|<C-w>_", { desc = "Zoom window" })
vim.keymap.set("n", "ZZ", "<cmd>wqa!<CR>", { desc = "Save all and quit" })

vim.keymap.set("n", "<leader>gb", "<cmd>Gitsigns toggle_current_line_blame<CR>", { desc = "Toggle git blame" })
vim.keymap.set("n", "<leader>gv", "<cmd>DiffviewOpen<CR>", { desc = "Open diffview" })
vim.keymap.set("n", "<leader>gV", "<cmd>DiffviewClose<CR>", { desc = "Close diffview" })
vim.keymap.set("n", "<leader>gH", "<cmd>DiffviewFileHistory %<CR>", { desc = "File history" })
vim.keymap.set("n", "]h", "<cmd>Gitsigns next_hunk<CR>", { desc = "Next hunk" })
vim.keymap.set("n", "[h", "<cmd>Gitsigns prev_hunk<CR>", { desc = "Previous hunk" })
vim.keymap.set("n", "<leader>hs", "<cmd>Gitsigns stage_hunk<CR>", { desc = "Stage hunk" })
vim.keymap.set("n", "<leader>hr", "<cmd>Gitsigns reset_hunk<CR>", { desc = "Reset hunk" })
vim.keymap.set("n", "<leader>hp", "<cmd>Gitsigns preview_hunk<CR>", { desc = "Preview hunk" })
vim.keymap.set("n", "<leader>hB", "<cmd>Gitsigns blame_line<CR>", { desc = "Blame line" })

vim.keymap.set("n", "<leader>xx", "<cmd>Trouble diagnostics toggle<CR>", { desc = "Diagnostics" })
vim.keymap.set("n", "<leader>xX", "<cmd>Trouble diagnostics toggle filter.buf=0<CR>", { desc = "Buffer diagnostics" })
vim.keymap.set("n", "<leader>xs", "<cmd>Trouble symbols toggle focus=false<CR>", { desc = "Symbols" })
vim.keymap.set("n", "<leader>xq", "<cmd>Trouble qflist toggle<CR>", { desc = "Quickfix list" })
vim.keymap.set("n", "<leader>xr", "<cmd>Trouble lsp_references toggle focus=false<CR>", { desc = "LSP references" })
vim.keymap.set("n", "<leader>xd", "<cmd>Trouble lsp_definitions toggle focus=false<CR>", { desc = "LSP definitions" })
vim.keymap.set("n", "<leader>xi", "<cmd>Trouble lsp_implementations toggle focus=false<CR>", { desc = "LSP implementations" })
vim.keymap.set("n", "<leader>xt", "<cmd>Trouble lsp_type_definitions toggle focus=false<CR>", { desc = "LSP type definitions" })

vim.keymap.set("n", "<leader>ff", pick_files, { desc = "Find files" })
vim.keymap.set("n", "<leader>fg", pick_grep, { desc = "Live grep" })
vim.keymap.set("n", "<leader>fb", function()
  Snacks.picker.buffers()
end, { desc = "Buffers" })
vim.keymap.set("n", "<leader>fr", function()
  Snacks.picker.recent()
end, { desc = "Recent files" })
vim.keymap.set("n", "<leader>fd", function()
  Snacks.picker.diagnostics_buffer()
end, { desc = "Buffer diagnostics" })
vim.keymap.set("n", "<leader>fh", function()
  Snacks.picker.help()
end, { desc = "Help" })
vim.keymap.set("n", "<leader>fk", function()
  Snacks.picker.keymaps()
end, { desc = "Keymaps" })
vim.keymap.set("n", "<leader>fi", function()
  Snacks.picker.grep()
end, { desc = "Grep (full)" })
vim.keymap.set("n", "<leader>ft", function()
  Snacks.explorer.open()
end, { desc = "Explorer" })

vim.keymap.set("n", "<leader>gd", function()
  Snacks.picker.git_diff()
end, { desc = "Git diff" })
vim.keymap.set("n", "<leader>gf", function()
  Snacks.picker.git_log_file()
end, { desc = "Git log (file)" })
vim.keymap.set("n", "<leader>gg", function()
  Snacks.lazygit()
end, { desc = "Lazygit" })
vim.keymap.set("n", "<leader>gl", function()
  Snacks.picker.git_log()
end, { desc = "Git log" })
vim.keymap.set("n", "<leader>gL", function()
  Snacks.picker.git_log_line()
end, { desc = "Git log (line)" })
vim.keymap.set("n", "<leader>gr", function()
  Snacks.picker.git_branches()
end, { desc = "Git branches" })
vim.keymap.set("n", "<leader>gS", function()
  Snacks.picker.git_stash()
end, { desc = "Git stash" })
vim.keymap.set("n", "<leader>gs", function()
  Snacks.picker.git_status()
end, { desc = "Git status" })

vim.keymap.set("n", "<leader>nA", "<cmd>NotesAllGrep<CR>", { desc = "All notes grep" })
vim.keymap.set("n", "<leader>na", "<cmd>NotesAllGrep float<CR>", { desc = "All notes grep (float)" })
vim.keymap.set("n", "<leader>nf", "<cmd>Notes float<CR>", { desc = "Notes (float)" })
vim.keymap.set("n", "<leader>nF", "<cmd>Notes<CR>", { desc = "Notes" })
vim.keymap.set("n", "<leader>ng", "<cmd>NotesGrep float<CR>", { desc = "Notes grep (float)" })
vim.keymap.set("n", "<leader>nG", "<cmd>NotesGrep<CR>", { desc = "Notes grep" })
vim.keymap.set("n", "<leader>nj", "<cmd>JournalGrep float<CR>", { desc = "Journal grep (float)" })
vim.keymap.set("n", "<leader>nJ", "<cmd>JournalGrep<CR>", { desc = "Journal grep" })
vim.keymap.set("n", "<leader>nn", "<cmd>LastNote float<CR>", { desc = "Last note (float)" })
vim.keymap.set("n", "<leader>np", "<cmd>ProjectNotes float<CR>", { desc = "Project notes (float)" })
vim.keymap.set("n", "<leader>nP", "<cmd>ProjectNotes<CR>", { desc = "Project notes" })
vim.keymap.set("n", "<leader>ns", "<cmd>ProjectNote scratch float<CR>", { desc = "Project scratch note (float)" })
vim.keymap.set("n", "<leader>nS", "<cmd>ProjectNote scratch<CR>", { desc = "Project scratch note" })
vim.keymap.set("n", "<leader>nt", "<cmd>ProjectNote todo float<CR>", { desc = "Project todo note (float)" })
vim.keymap.set("n", "<leader>nT", "<cmd>ProjectNote todo<CR>", { desc = "Project todo note" })

vim.keymap.set("n", "<C-.>", function()
  Snacks.scratch()
end, { desc = "Scratch buffer" })
vim.keymap.set("n", "<C-/>", function()
  Snacks.terminal()
end, { desc = "Terminal" })

vim.keymap.set("n", "<C-a>", function()
  require("dial.map").manipulate("increment", "normal")
end, { desc = "Increment" })
vim.keymap.set("n", "<C-x>", function()
  require("dial.map").manipulate("decrement", "normal")
end, { desc = "Decrement" })
vim.keymap.set("v", "<C-a>", function()
  require("dial.map").manipulate("increment", "visual")
end, { desc = "Increment" })
vim.keymap.set("v", "<C-x>", function()
  require("dial.map").manipulate("decrement", "visual")
end, { desc = "Decrement" })

vim.keymap.set("n", "gj", function()
  require("treesj").join()
end, { desc = "Treesj join" })
vim.keymap.set("n", "gs", function()
  require("treesj").split()
end, { desc = "Treesj split" })
vim.keymap.set("n", "gt", function()
  require("treesj").toggle()
end, { desc = "Treesj toggle" })

vim.keymap.set("n", "<leader>aa", function()
  require("sidekick.cli").toggle({ name = "opencode", focus = true })
end, { desc = "Open OpenCode CLI" })
vim.keymap.set("x", "<leader>aa", function()
  require("sidekick.cli").toggle({ name = "opencode", focus = true })
end, { desc = "Open OpenCode CLI" })
vim.keymap.set("x", "<leader>as", function()
  require("sidekick.cli").send()
end, { desc = "Send selection to CLI" })
vim.keymap.set("n", "<leader>at", function()
  require("sidekick.cli").select()
end, { desc = "Select AI tool" })
vim.keymap.set("n", "<leader>ap", function()
  require("sidekick.cli").prompt()
end, { desc = "Select prompt" })
vim.keymap.set("n", "<leader>ad", function()
  require("sidekick.cli").close()
end, { desc = "Close CLI session" })

vim.keymap.set("n", "<tab>", function()
  if not require("sidekick").nes_jump_or_apply() then
    local keys = vim.api.nvim_replace_termcodes("<C-i>", true, false, true)
    vim.api.nvim_feedkeys(keys, "n", false)
    return ""
  end
  return ""
end, { desc = "Goto/Apply Next Edit Suggestion", expr = true })
