local pick_files = function()
  if vim.fn.finddir(".git", vim.fn.getcwd() .. ";") ~= "" then
    Snacks.picker.git_files()
  else
    Snacks.picker.files()
  end
end

local pick_grep = function()
  if vim.fn.finddir(".git", vim.fn.getcwd() .. ";") ~= "" then
    Snacks.picker.git_grep()
  else
    Snacks.picker.grep()
  end
end

vim.keymap.set("c", "<S-Enter>", function()
  require("noice").redirect(vim.fn.getcmdline())
end, { desc = "Redirect command to Noice" })

vim.keymap.set("i", "<c-k>", function()
  return vim.lsp.buf.signature_help()
end, { desc = "Show signature help" })

vim.keymap.set("n", "<c-.>", function()
  Snacks.scratch()
end, { desc = "Toggle scratch buffer" })
vim.keymap.set("n", "<c-/>", function()
  Snacks.terminal()
end, { desc = "Toggle terminal" })
vim.keymap.set("n", "<A-h>", require("smart-splits").resize_left)
vim.keymap.set("n", "<A-j>", require("smart-splits").resize_down)
vim.keymap.set("n", "<A-k>", require("smart-splits").resize_up)
vim.keymap.set("n", "<A-l>", require("smart-splits").resize_right)
vim.keymap.set("n", "<C-\\>", require("smart-splits").move_cursor_previous)
vim.keymap.set("n", "<C-h>", require("smart-splits").move_cursor_left)
vim.keymap.set("n", "<C-j>", require("smart-splits").move_cursor_down)
vim.keymap.set("n", "<C-k>", require("smart-splits").move_cursor_up)
vim.keymap.set("n", "<C-l>", require("smart-splits").move_cursor_right)
vim.keymap.set("n", "<C-n>", "<cmd>bn<CR>", { desc = "Next buffer" })
vim.keymap.set("n", "<C-p>", "<cmd>bp<CR>", { desc = "Previous buffer" })
vim.keymap.set("n", "<leader>ka", function()
  require("sidekick.cli").toggle({ name = "opencode", focus = true })
end, { desc = "Toggle OpenCode" })
vim.keymap.set("n", "<leader>kd", function()
  require("sidekick.cli").close()
end, { desc = "Close sidekick" })
vim.keymap.set("n", "<leader>kf", function()
  require("sidekick.cli").send({ msg = "{file}" })
end, { desc = "Send file to sidekick" })
vim.keymap.set("n", "<leader>kp", function()
  require("sidekick.cli").prompt()
end, { desc = "Sidekick prompt" })
vim.keymap.set("n", "<leader>kt", function()
  require("sidekick.cli").send({ msg = "{this}" })
end, { desc = "Send selection to sidekick" })
vim.keymap.set("n", "<leader>b", function()
  Snacks.picker.buffers()
end, { desc = "Pick buffer" })
vim.keymap.set("n", "<leader>c", "<cmd>close<CR>", { desc = "Close window" })
vim.keymap.set("n", "<leader>d", "<cmd>bd<CR>", { desc = "Delete buffer" })
vim.keymap.set("n", "<leader>D", function()
  Snacks.bufdelete(0, { force = true })
end, { desc = "Delete buffer (force)" })
vim.keymap.set("n", "<leader>e", "<cmd>lua vim.diagnostic.open_float()<CR>", { desc = "Show diagnostics" })
vim.keymap.set("n", "<leader>fd", function()
  Snacks.picker.diagnostics_buffer()
end, { desc = "Pick buffer diagnostics" })
vim.keymap.set("n", "<leader>ff", function()
  pick_files()
end, { desc = "Pick files" })
vim.keymap.set("n", "<leader>fg", function()
  pick_grep()
end, { desc = "Grep files" })
vim.keymap.set("n", "<leader>fG", function()
  Snacks.picker.grep_buffers()
end, { desc = "Grep all buffers" })
vim.keymap.set("n", "<leader>fi", function()
  Snacks.picker.grep()
end, { desc = "Search in buffers" })
vim.keymap.set("n", "<leader>fj", function()
  Snacks.picker.jumps()
end, { desc = "Pick jump" })
vim.keymap.set("n", "<leader>fl", function()
  Snacks.picker.loclist()
end, { desc = "Pick location list" })
vim.keymap.set("n", "<leader>fm", function()
  Snacks.picker.marks()
end, { desc = "Pick mark" })
vim.keymap.set("n", "<leader>fP", function()
  Snacks.picker.projects()
end, { desc = "Pick project" })
vim.keymap.set("n", "<leader>fq", function()
  Snacks.picker.qflist()
end, { desc = "Pick quickfix" })
vim.keymap.set("n", "<leader>fr", function()
  Snacks.picker.recent()
end, { desc = "Pick recent files" })
vim.keymap.set("n", "<leader>ft", function()
  Snacks.explorer.open()
end, { desc = "Toggle explorer" })
vim.keymap.set("n", "<leader>fu", function()
  Snacks.picker.undo()
end, { desc = "Pick undo" })
vim.keymap.set("n", "<leader>gb", function()
  Snacks.git.blame_line()
end, { desc = "Git blame (current line)" })
vim.keymap.set("n", "<leader>gd", function()
  Snacks.picker.git_diff()
end, { desc = "Pick git diff" })
vim.keymap.set("n", "<leader>gf", function()
  Snacks.picker.git_log_file()
end, { desc = "Git log (current file)" })
vim.keymap.set("n", "<leader>gg", function()
  Snacks.lazygit()
end, { desc = "Lazy Git" })
vim.keymap.set("n", "<leader>gl", function()
  Snacks.gitbrowse()
end, { desc = "Open in git browser" })
vim.keymap.set("n", "<leader>gl", function()
  Snacks.picker.git_log()
end, { desc = "Git log" })
vim.keymap.set("n", "<leader>gL", function()
  Snacks.picker.git_log_line()
end, { desc = "Git log (current line)" })
vim.keymap.set("n", "<leader>gr", function()
  Snacks.picker.git_branches()
end, { desc = "Pick git branch" })
vim.keymap.set("n", "<leader>gS", function()
  Snacks.picker.git_stash()
end, { desc = "Pick git stash" })
vim.keymap.set("n", "<leader>gs", function()
  Snacks.picker.git_status()
end, { desc = "Git status" })
vim.keymap.set("n", "<leader>gv", function()
  if next(require("diffview.lib").views) == nil then
    vim.cmd("DiffviewOpen")
  else
    vim.cmd("DiffviewClose")
  end
end, { desc = "Toggle diffview" })
vim.keymap.set("n", "<leader>la", vim.lsp.buf.code_action, { desc = "Code action" })
vim.keymap.set("n", "<leader>lC", vim.lsp.codelens.refresh, { desc = "Refresh codelens" })
vim.keymap.set("n", "<leader>lc", vim.lsp.codelens.run, { desc = "Run codelens" })
vim.keymap.set("n", "<leader>lf", function()
  vim.lsp.buf.format()
end, { desc = "Format buffer" })
vim.keymap.set("n", "<leader>ll", function()
  Snacks.picker.lsp_config()
end, { desc = "LSP configuration" })
vim.keymap.set("n", "<leader>lR", function()
  Snacks.rename.rename_file()
end, { desc = "Rename file" })
vim.keymap.set("n", "<leader>lr", vim.lsp.buf.rename, { desc = "Rename" })
vim.keymap.set("n", "<leader>ls", function()
  Snacks.picker.lsp_symbols()
end, { desc = "LSP symbols" })
vim.keymap.set("n", "<leader>lS", function()
  Snacks.picker.lsp_workspace_symbols()
end, { desc = "LSP workspace symbols" })
vim.keymap.set("n", "<leader>nA", "<cmd>NotesAllGrep <CR>", { desc = "All notes grep" })
vim.keymap.set("n", "<leader>na", "<cmd>NotesAllGrep float<CR>", { desc = "All notes grep (float)" })
vim.keymap.set("n", "<leader>nf", "<cmd>Notes float<CR>", { desc = "Notes (float)" })
vim.keymap.set("n", "<leader>nF", "<cmd>Notes<CR>", { desc = "Notes" })
vim.keymap.set("n", "<leader>ng", "<cmd>NotesGrep float<CR>", { desc = "Notes grep (float)" })
vim.keymap.set("n", "<leader>nG", "<cmd>NotesGrep<CR>", { desc = "Notes grep" })
vim.keymap.set("n", "<leader>nj", "<cmd>JournalGrep float<CR>", { desc = "Journal grep (float)" })
vim.keymap.set("n", "<leader>nJ", "<cmd>JournalGrep<CR>", { desc = "Journal grep" })
vim.keymap.set("n", "<leader>nn", "<cmd>LastNote float<CR>", { desc = "Last note (float)" })
vim.keymap.set("n", "<leader>np", "<cmd>ProjectNotes float<CR>", { desc = "Project notes (float)" })
vim.keymap.set("n", "<leader>nP", "<cmd>ProjectNotes<CR>", { desc = "Project notes" })
vim.keymap.set("n", "<leader>ns", "<cmd>ProjectNote scratch float<CR>", { desc = "Project scratch note (float)" })
vim.keymap.set("n", "<leader>nS", "<cmd>ProjectNote scratch<CR>", { desc = "Project scratch note" })
vim.keymap.set("n", "<leader>nt", "<cmd>Journal float<CR>", { desc = "Journal (float)" })
vim.keymap.set("n", "<leader>nT", "<cmd>Journal<CR>", { desc = "Journal" })
vim.keymap.set("n", "<leader>nt", "<cmd>ProjectNote todo float<CR>", { desc = "Project todo note (float)" })
vim.keymap.set("n", "<leader>nT", "<cmd>ProjectNote todo<CR>", { desc = "Project todo note" })
vim.keymap.set("n", "<leader>P", '"+P', { desc = "Paste clipboard before cursor" })
vim.keymap.set("n", "<leader>p", '"+p', { desc = "Paste clipboard" })
vim.keymap.set("n", "<leader>un", "<cmd>set number!<CR>", { desc = "Toggle line numbers" })
vim.keymap.set("n", "<leader>uNa", function()
  require("noice").cmd("all")
end, { desc = "Noice all" })
vim.keymap.set("n", "<leader>uNd", function()
  require("noice").cmd("dismiss")
end, { desc = "Dismiss Noice" })
vim.keymap.set("n", "<leader>uNh", function()
  require("noice").cmd("history")
end, { desc = "Noice history" })
vim.keymap.set("n", "<leader>uNl", function()
  require("noice").cmd("last")
end, { desc = "Noice last" })
vim.keymap.set("n", "<leader>wo", "<C-w>o", { desc = "Close other windows" })
vim.keymap.set("n", "<leader>wp", "<cmd>pclose<CR>", { desc = "Close preview window" })
vim.keymap.set("n", "<leader>wz", "<C-w>|<C-w>_", { desc = "Maximize window" })
vim.keymap.set("n", "<leader>y", '"+y', { desc = "Copy to clipboard" })
vim.keymap.set("n", "<tab>", function()
  if not require("sidekick").nes_jump_or_apply() then
    return "<Tab>"
  end
end, { desc = "Sidekick jump or apply" })
vim.keymap.set("n", "[[", function()
  Snacks.words.jump(-vim.v.count1)
end, { desc = "Jump to previous word" })
vim.keymap.set("n", "[l", "<cmd>lprevious<CR>", { desc = "Previous location" })
vim.keymap.set("n", "[q", "<cmd>cprevious<CR>", { desc = "Previous quickfix" })
vim.keymap.set("n", "]]", function()
  Snacks.words.jump(vim.v.count1)
end, { desc = "Jump to next word" })
vim.keymap.set("n", "]l", "<cmd>lnext<CR>", { desc = "Next location" })
vim.keymap.set("n", "]q", "<cmd>cnext<CR>", { desc = "Next quickfix" })
vim.keymap.set("n", "gd", function()
  Snacks.picker.lsp_definitions()
end, { desc = "Go to definition" })
vim.keymap.set("n", "gD", vim.lsp.buf.declaration, { desc = "Go to declaration" })
vim.keymap.set("n", "gI", function()
  Snacks.picker.lsp_implementations()
end, { desc = "Go to implementation" })
vim.keymap.set("n", "gK", function()
  return vim.lsp.buf.signature_help()
end, { desc = "Signature help" })
vim.keymap.set("n", "gr", function()
  Snacks.picker.lsp_references()
end, { desc = "Go to references" })
vim.keymap.set("n", "gy", function()
  Snacks.picker.lsp_type_definitions()
end, { desc = "Go to type definition" })
vim.keymap.set("n", "K", function()
  return vim.lsp.buf.hover()
end, { desc = "Hover" })
vim.keymap.set("n", "ZZ", "<cmd>wqa!<CR>", { desc = "Quit all and save" })
vim.keymap.set("n", '<leader>f"', function()
  Snacks.picker.registers()
end, { desc = "Pick register" })
vim.keymap.set("n", "<leader><leader>h", require("smart-splits").swap_buf_left, { desc = "Swap buffer left" })
vim.keymap.set("n", "<leader><leader>j", require("smart-splits").swap_buf_down, { desc = "Swap buffer down" })
vim.keymap.set("n", "<leader><leader>k", require("smart-splits").swap_buf_up, { desc = "Swap buffer up" })
vim.keymap.set("n", "<leader><leader>l", require("smart-splits").swap_buf_right, { desc = "Swap buffer right" })

vim.keymap.set("t", "<Esc>", "<C-\\><C-n>", { desc = "Exit terminal mode" })

vim.keymap.set("x", "<leader>ap", function()
  require("sidekick.cli").prompt()
end, { desc = "Sidekick prompt (visual)" })
vim.keymap.set("x", "<leader>at", function()
  require("sidekick.cli").send({ msg = "{this}" })
end, { desc = "Send selection to sidekick (visual)" })
vim.keymap.set("x", "<leader>av", function()
  require("sidekick.cli").send({ msg = "{selection}" })
end, { desc = "Send selection to sidekick (visual)" })
vim.keymap.set("x", "<leader>la", vim.lsp.buf.code_action, { desc = "Code action (visual)" })
vim.keymap.set("x", "<leader>lc", vim.lsp.codelens.run, { desc = "Run codelens (visual)" })
vim.keymap.set("x", "<leader>s", ":'<,'>sort i<CR>", { desc = "Sort selection" })
vim.keymap.set("x", "<leader>y", '"+y', { desc = "Copy to clipboard (visual)" })
