vim.pack.add({
  "https://github.com/b0o/SchemaStore.nvim",
  "https://github.com/burnskp/notes.nvim",
  "https://github.com/catppuccin/nvim",
  "https://github.com/copilotlsp-nvim/copilot-lsp",
  "https://github.com/echasnovski/mini.ai",
  "https://github.com/echasnovski/mini.bracketed",
  "https://github.com/fang2hou/blink-copilot",
  "https://github.com/folke/snacks.nvim",
  "https://github.com/folke/trouble.nvim",
  "https://github.com/folke/which-key.nvim",
  "https://github.com/Kaiser-Yang/blink-cmp-avante",
  "https://github.com/kylechui/nvim-surround",
  "https://github.com/lewis6991/gitsigns.nvim",
  "https://github.com/MeanderingProgrammer/render-markdown.nvim",
  "https://github.com/mfussenegger/nvim-lint",
  "https://github.com/monaqa/dial.nvim",
  "https://github.com/mrjones2014/smart-splits.nvim",
  "https://github.com/MunifTanjim/nui.nvim",
  "https://github.com/neovim/nvim-lspconfig",
  "https://github.com/numToStr/Comment.nvim",
  "https://github.com/nvim-lua/plenary.nvim",
  "https://github.com/nvim-lualine/lualine.nvim",
  "https://github.com/nvim-tree/nvim-web-devicons",
  "https://github.com/nvim-treesitter/nvim-treesitter-context",
  "https://github.com/nvim-treesitter/nvim-treesitter-textobjects",
  "https://github.com/sindrets/diffview.nvim",
  "https://github.com/stevearc/conform.nvim",
  "https://github.com/Wansmer/treesj",
  "https://github.com/yetone/avante.nvim",
  { src = "https://github.com/nvim-treesitter/nvim-treesitter", version = "main" },
  { src = "https://github.com/saghen/blink.cmp", version = vim.version.range("~1") },
}, { confirm = false })
