vim.pack.add({
  "https://github.com/b0o/SchemaStore.nvim",
  "https://github.com/burnskp/notes.nvim",
  "https://github.com/catppuccin/nvim",
  "https://github.com/folke/noice.nvim",
  "https://github.com/folke/sidekick.nvim",
  "https://github.com/folke/snacks.nvim",
  "https://github.com/folke/which-key.nvim",
  "https://github.com/Kaiser-Yang/blink-cmp-avante",
  "https://github.com/kylechui/nvim-surround",
  "https://github.com/lewis6991/gitsigns.nvim",
  "https://github.com/marilari88/neotest-vitest",
  "https://github.com/MeanderingProgrammer/render-markdown.nvim",
  "https://github.com/mfussenegger/nvim-lint",
  "https://github.com/mrjones2014/smart-splits.nvim",
  "https://github.com/MunifTanjim/nui.nvim",
  "https://github.com/neovim/nvim-lspconfig",
  "https://github.com/numToStr/Comment.nvim",
  "https://github.com/nvim-focus/focus.nvim",
  "https://github.com/nvim-lua/plenary.nvim",
  "https://github.com/nvim-lualine/lualine.nvim",
  "https://github.com/nvim-neotest/neotest",
  "https://github.com/nvim-neotest/neotest-go",
  "https://github.com/nvim-neotest/neotest-python",
  "https://github.com/nvim-neotest/nvim-nio",
  "https://github.com/nvim-tree/nvim-web-devicons",
  "https://github.com/nvim-treesitter/nvim-treesitter-context",
  "https://github.com/sindrets/diffview.nvim",
  "https://github.com/stevearc/conform.nvim",
  "https://github.com/stevearc/dressing.nvim",
  "https://github.com/yetone/avante.nvim",
  "https://github.com/zbirenbaum/copilot.lua",
  { src = "https://github.com/nvim-treesitter/nvim-treesitter", version = "main" },
  { src = "https://github.com/saghen/blink.cmp", version = vim.version.range("~1") },
}, { confirm = false })
