vim.pack.add({
  "https://github.com/nvim-treesitter/nvim-treesitter-context",
 { src = "https://github.com/nvim-treesitter/nvim-treesitter", version = 'main' },
}, { confirm = false })

require("nvim-treesitter").install({
  "bash",
  "diff",
  "dockerfile",
  "git_config",
  "git_rebase",
  "gitattributes",
  "gitcommit",
  "gitignore",
  "go",
  "gomod",
  "gosum",
  "gotmpl",
  "hcl",
  "helm",
  "json",
  "json5",
  "jsonc",
  "lua",
  "luadoc",
  "make",
  "markdown",
  "markdown_inline",
  "python",
  "regex",
  "ssh_config",
  "terraform",
  "toml",
  "vim",
  "vimdoc",
  "xml",
  "yaml",
})
